apiVersion: v1
kind: Service
metadata:
  name: cloudocr
  labels:
    app: cloudocr
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  selector:
    app: cloudocr
  type: LoadBalancer